# Generated by Django 6.0.1 on 2026-03-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_email_alarma'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='jueves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='lunes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='martes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='miercoles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alarma',
            name='viernes',
            field=models.BooleanField(default=False),
        ),
    ]
